### ISSUE TITLE
First device permission request always unsuccessful

### ISSUE THREAD

**Issue by alexey-pelykh** [alexey-pelykh/UVCCamera#2]
This happens when the application has no permission for the USB device because the library specifies `PendingIntent.FLAG_IMMUTABLE` on the `PendingIntent` used for requesting the permission. As a result, no `UsbManager.EXTRA_PERMISSION_GRANTED` is placed into the received intent, causing library to consider that a failed request.

Side effect: since neither `UsbManager.EXTRA_DEVICE` is present, `onCancel(null)` is effectively called nullable parameter is not expected.

**Comment by alexey-pelykh** [comment]
A note to @hthetiot: as this change originally taken from [these lines of your PR](https://github.com/saki4510t/UVCCamera/pull/709/files#diff-d4f2017386ccad7ac1b166f6ae5b7543a359720b1267ea3ca821129ecbd15cbaL170-R171), I wanted to let you know that it's an issue.

**Comment by hthetiot** [comment]
@alexey-pelykh thank you i will use git cherry pick to merge the fix.
Taking changes without git cherry pick remove the original author, i dont recommend to keep open source change more traceable.

**Comment by hthetiot** [comment]
Can't use cherry pick cause copy pasta.

**Comment by alexey-pelykh** [comment]
I think you're having an issue with cherry-pick because of the sources reorganization (namely, `libuvccamera` becoming just `lib`), yet this is a hard fork - I don't intend to keep the structure of the original project. And while some sources were copied as is, attribution is kept here https://github.com/alexey-pelykh/UVCCamera/tree/main/upstreams - and I assume you'd call how jni folder is organized in the original project as well a "copy pasta" because those libraries where imported as sources.

**Comment by hthetiot** [comment]
Thank you @alexey-pelykh for the lead I will check and consider resolve conflict.

Also link to commmet on for context:
https://github.com/alexey-pelykh/UVCCamera/issues/2#issuecomment-2512264838

> the original project as well a "copy pasta" because those libraries where imported as sources

I see what you mean, at the time I don't think people understood how using git sub module for that use case, or original lib might not used git, and unfortunately it is common for C/Native wrapper to do that. But again no hard feelings, just speaking my mind 😌 and yes it would be good practice, but you do have to modify header in many cases so more excusable.

**Comment by alexey-pelykh** [comment]
> more excusable

can't really agree, there's a way - download sources from wherever (git or no git) they are and apply patch files during the build.

Anyhow, we don't know why @saki4510t did like that, nor I particularly care - it's a great library that deserves some maintenance and promotion.

**Comment by hthetiot** [comment]
>.Anyhow, we don't know why @saki4510t did like that, nor I particularly care

I did the like...

**Comment by alexey-pelykh** [comment]
@hthetiot it appears that my fix was not fully correct, please see #24 and #28 if that's still relevant to you
