### ISSUE TITLE
Unable to Use Library - Incomplete Example on pub.dev and GitHub

### ISSUE THREAD

**Issue by LucasDeSouzaVieira9** [alexey-pelykh/UVCCamera#21]
I attempted to use this library, but I couldn't get it working. The example provided on pub.dev does not include the necessary configuration steps, and the GitHub repository has an incomplete setup for dependencies. For anyone looking to integrate this library, it would be very helpful if the pub.dev example was fully executable, with all configurations clearly explained and dependencies properly set up.

**Comment by alexey-pelykh** [comment]
Sorry to hear about the difficulties you've experienced! The example is split into several files and can be found in  [/flutter/example](https://github.com/alexey-pelykh/UVCCamera/tree/main/flutter/example) as the amount of code is too big to fit into a single `main.dart` file that is shown on pub.dev

As for

> and the GitHub repository has an incomplete setup for dependencies

Could you please clarify in what way it is incomplete? The fact that CI passes indicates that all that should be there for building is there.

**Comment by alexey-pelykh** [comment]
Let me know if this readme helps: https://github.com/alexey-pelykh/UVCCamera/pull/22/files?short_path=68d95cf#diff-68d95cf3717c46b17794d75a60f019b854cefd6f81da6248e7cdc3b70938eee6

**Comment by LucasDeSouzaVieira9** [comment]
I downloaded the /flutter/example and tried to build it but was unsuccessful. I also tried creating a new project from scratch, but that didn’t work either. I'll try again and get back to you with feedback.

If possible, could you include in the project's README what needs to be configured (if anything) in the android folder? That would help clarify any necessary setup steps.

Thanks!

**Comment by LucasDeSouzaVieira9** [comment]
I downloaded the /flutter/example and tried to build it but was unsuccessful. I also tried creating a new project from scratch, but that didn’t work either. I'll try again and get back to you with feedback.

If possible, could you include in the project's README what needs to be configured (if anything) in the android folder? That would help clarify any necessary setup steps.

Thanks!

**Comment by alexey-pelykh** [comment]
Using file sources as mentioned here https://github.com/alexey-pelykh/UVCCamera/blob/main/flutter/example/README.md should produce a working app. If that does not work for you, logs with errors would be quite helpful.

**Comment by Ramsay99** [comment]
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.uvccamera:lib:0.0.0-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/uvccamera/lib/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/org/uvccamera/lib/0.0.0-SNAPSHOT/lib-0.0.0-SNAPSHOT.pom
       - file:/C:/Users/Drago/.m2/repository/org/uvccamera/lib/0.0.0-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/Drago/.m2/repository/org/uvccamera/lib/0.0.0-SNAPSHOT/lib-0.0.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/uvccamera/lib/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/uvccamera/lib/0.0.0-SNAPSHOT/lib-0.0.0-SNAPSHOT.pom
       - https://storage.googleapis.com/download.flutter.io/org/uvccamera/lib/0.0.0-SNAPSHOT/maven-metadata.xml
       - https://storage.googleapis.com/download.flutter.io/org/uvccamera/lib/0.0.0-SNAPSHOT/lib-0.0.0-SNAPSHOT.pom
     Required by:
         project :app > project :uvccamera

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
Error: Gradle task assembleDebug failed with exit code 1
![image](https://github.com/user-attachments/assets/d0b6f7f9-a3f4-46eb-a221-f2853bd2dabd)

**Comment by alexey-pelykh** [comment]
@Ramsay99 you're trying to run an example from a cloned repository that is by default configured for local development (`0.0.0-SNAPSHOT`). If that is your intention - modifying the library, I suggest you to build the native library first using `./gradlew :lib:publishToMavenLocal`. And if that's not your intention - I strongly suggest using a published version of the library as indicated on https://github.com/alexey-pelykh/UVCCamera/blob/main/flutter/example/README.md

**Comment by alexey-pelykh** [comment]
I've added a new section [Development & Contribution](https://github.com/alexey-pelykh/UVCCamera/?tab=readme-ov-file#development--contribution) that covers the basics how to start with a cloned repo.

As for the cases when a published Flutter plugin is used, please refer to [Flutter example](https://pub.dev/packages/uvccamera/example)
