### ISSUE TITLE
Support Flutter's impeller

### ISSUE THREAD

**Issue by alexey-pelykh** [alexey-pelykh/UVCCamera#34]
See https://docs.flutter.dev/release/breaking-changes/android-surface-plugins

**Comment by alexey-pelykh** [comment]
@qamarkhan1 please test https://github.com/alexey-pelykh/UVCCamera/actions/runs/12491701300/artifacts/2361167715 from #36 on the Oppo F19 device.

**Comment by qamarkhan1** [comment]
I'm sorry to say, but it gives black page still, and I want to tell you this is not issue from package, this is because of Flutter 3.27.#. If we ran it on any previous versions, it'll work, but for flutter 3.27.# it worls only when run with "flutter run --no-enable-impeller"

**Comment by qamarkhan1** [comment]
> I'm sorry to say, but it gives black page still, and I want to tell you this is not issue from package, this is because of Flutter 3.27.#. If we ran it on any previous versions, it'll work, but for flutter 3.27.# it worls only when run with "flutter run --no-enable-impeller"

and want to add something more that this issue I do not faced on any other devices, tried multiple, occurs only on Oppo F19 Pro

**Comment by alexey-pelykh** [comment]
Thanks for the testing! That is curious that only one device experiences the issue. I've tried force-enabling (`--enable-impeller`) and disabling it (`--no-enable-impleller`) on my devices and this PR didn't change anything except removing the warning message. 🤔

**Comment by alexey-pelykh** [comment]
Seems like it's an issue with Flutter itself as per https://github.com/flutter/flutter/issues/160228#issuecomment-2550383534

**Comment by alexey-pelykh** [comment]
@qamarkhan1 you've tested the supplied APK or local build? If local build - was that with Flutter 3.27.1 or 3.27.0?

It would seem that since Oppo F19 has Adreno 610 and given that this fix https://github.com/flutter/flutter/issues/160041 was done in Flutter 3.27.1 - the 3.27.0 won't work for you

**Comment by qamarkhan1** [comment]
then that's strange too, I tested supplied apk and locally running on 3.27.1, both have black page.

**Comment by nvanderwaal** [comment]
We got multiple reports from users experiencing black screens on 3.27.1, devices like Samsung Galaxy A51, Samsung S22 Ultra. We had to downgrade to Flutter 3.24 sadly, disabling Impeller alone didn't work

**Comment by alexey-pelykh** [comment]
@nvanderwaal thanks for the report! It would be great if you could create a new bug report with logs and indicate which library versions have been tested
