### ISSUE TITLE
I Fail to run the example

### ISSUE THREAD

**Issue by Ramsay99** [alexey-pelykh/UVCCamera#37]
###  First, let me list my tools version:

- _Flutter Doctor:_
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.19045.5247], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.5)
[√] Android Studio (version 2024.2)
[√] VS Code (version 1.96.2)
[√] Connected device (3 available)
[√] Network resources

! Doctor found issues in 1 category.
```

- _Flutter --version:_
```
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (9 days ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2
```

- Java Version: ` java version "23.0.1" 2024-10-15`
- Android Studio: `Ladybug 2024.2.1 Patch 3`
- Android Device Emulator: `API 35 "VanillaIceCream" Android 15.0`

### Here what i have done so far:

1. Create new flutter project (android studio latest version)
2. Follow the Usage instructions here: [https://github.com/alexey-pelykh/UVCCamera?tab=readme-ov-file#usage](url) 
3. I dont know where I should place this `implementation 'org.uvccamera:lib:0.1.0'` so i have tried in these three files and didn't work: 
- android/build.gradle
- android/app/build.gradle
- android/settings.gradle

4. Tried many solutions over ChatGPT, overflow, ... (did not succeed)
5. Asking for you kind assistance : ) 

![image](https://github.com/user-attachments/assets/4e24f8fa-241b-4202-9063-494b8145e6f3)

**Comment by alexey-pelykh** [comment]
I am fairly certain that's not what you need to do to add a dependency to a Flutter application. I suggest you to follow https://pub.dev/packages/uvccamera/example and some tutorials on how to start with Flutter development - I'm in no position to guide you there, unfortunately.
